### ISSUE TITLE
Support multi-project repositories

### ISSUE THREAD

**Issue by Kixunil** [crywolf/mkchlog#14]
Some repositories host multiple projects that are related but have disjoint changelogs. This is typical for multi-crate workspacess in Rust. We should support this.

**Proposed solution**

Add `projects: []` key to the config yml listing all projects in the repository. (Must NOT be empty)
Add `project:` key to the commit.

If `projects` is defined then git commit must contain `project: x` where x is one of the specified project names.
Additionally it'd be nice to have `projects-after: commit` and `first-project: name` to help with migration - if they are specified then commits up to `projects-after` are considered belonging to `first-project`.

Later we can have tooling to auto-detect projects/changes so configuration and writing changelogs is easier.

**Comment by crywolf** [comment]
And when running `mkchlog` you would need to specify project name to generate changelog only for specified project, right?

**Comment by Kixunil** [comment]
Yes.

**Comment by crywolf** [comment]
I have implemented it in #20 

Configuration in YAML looks little bit different than you specified, please refer to `README.md` where it is described, or to YAML files in `tests` directory.

One thing I do not know how to solve, is the wasm version. App needs to accept argument `--project`. Instead of argument I simply put `None` there. See here: https://github.com/crywolf/mkchlog/pull/20/files#diff-3920f5b0c1e7a80683f05ae43cb02274ad7d418643021a88b4cf765008c79779R35

Let me know what you think.

**Comment by crywolf** [comment]
I redesigned and improved the multi-project implementation #20 so it checks if the files changed by the commit fulfil the validation rules, mainly that the commit can change only files belonging to the project name provided in changelog commit message. I want to use it in git hook to prefill the commit message. It is already used in `commit-msg` git hook, so it checks this rule during committing.

Config YAML looks like this:

```yaml
# .mkchlog.yml
# top level
projects:
    list:  # list of allowed projects
    - main: [".", .github, .githooks] # name: [directory1, directory2, ...]
    - mkchlog: [mkchlog] # name: [directory]
    - mkchlog-action: [mkchlog-action] # name: [directory]

    since-commit: 11964cbb5ac05c5a19d75b5bebcc74ebc867e438 # projects are mandatory since COMMIT_NUMBER [optional]
    default: mkchlog # commits up to COMMIT_NUMBER are considered belonging to the project NAME [optional]
```

If projects list is provided then git commit must contain `project: x` in the changelog message where `x` is one of the specified project names. After a project name the list of directories the project is contained in must be provided. Project `main` in the example above is the "root" project that contains all files in the project root directory plus other directories that do not belong to other projects.
